export const data = {
  slug: "pump-service",
  url:  "/services/pump-service",
  fallback: {
    title:       "Industrial Pump Repair · 40+ Yrs · Free Pickup",
    description: "Centrifugal, vertical turbine, split-case & positive-displacement pump repair. 24-mo written warranty, free nationwide pickup, 24/7 emergency.",
    ogImage:     "/images/oilfield-pumps.webp",
  },
  hero: {
    h1:         "Industrial Pump Repair & Rebuild — All Brands, Nationwide",
    subheading: "Centrifugal, vertical turbine, split-case, and positive-displacement pump repair from a shop that's been rebuilding rotating equipment for forty years. Free nationwide pickup, 24-month written warranty, 24/7 emergency response.",
    bgImage:    "/images/oilfield-pumps.webp",
  },
  intro: [
    "When an industrial pump fails, production stops. It doesn't matter if it's a 5-horsepower booster pump on a cooling tower or a 1,200-horsepower vertical turbine on a refinery feed line — the equipment downstream of that pump is now offline, and the clock is running. Kelsey Machine Services has been repairing industrial pumps for forty years. We rebuild centrifugal pumps, vertical turbines, split-case pumps, and positive-displacement pumps to OEM specifications, with the precision balancing, hard-facing, and documentation that demanding process industries require.",
    "Our pump repair process is comprehensive — every rebuild starts with a complete teardown and documented as-found inspection, and ends with dynamic balancing, dimensional verification, and a 24-month written warranty. We work on equipment from every major manufacturer including Goulds, Sulzer, Flowserve, ITT, KSB, and dozens of others. If your pump uses standard ANSI or API construction, our shop can repair it.",
    "What sets Kelsey Machine apart is the same thing that's set us apart for four decades: we don't just rebuild what's in front of us, we figure out why it failed and address the root cause. Cavitation damage is often a system problem, not a pump problem. Bearing failures are usually about lubrication or alignment, not the bearing itself. We tell you what we find — and we put it in writing.",
  ],
  quickAnswer: "Kelsey Machine Services provides full-service industrial pump repair and rebuild for centrifugal, vertical turbine, split-case, and positive-displacement pumps. We service all major manufacturers including Goulds, Sulzer, Flowserve, ITT, KSB, and others. Standard turnaround is 2-3 weeks; emergency service available for production-critical units. Every rebuild is backed by a 24-month written warranty and dynamically balanced to ISO 1940 G2.5.",
  equipmentTypes: [
    { name: "Centrifugal Pumps",          desc: "Single-stage, multi-stage, end-suction, between-bearings, and split-case designs — every common configuration found in industrial process service." },
    { name: "Vertical Turbine Pumps",     desc: "Deep-well, can-mount, and barrel pumps used for water supply, condensate return, and high-head process applications." },
    { name: "Horizontal Split Case",      desc: "Double-suction split-case pumps used in high-flow, low-NPSH applications including water treatment and HVAC service." },
    { name: "Positive Displacement",      desc: "Gear, lobe, screw, vane, and diaphragm pumps used for high-viscosity fluids, metering, and low-shear product transfer." },
    { name: "Self-Priming & Trash Pumps", desc: "Industrial and municipal pumps used for sewage, slurry, and intermittent-duty applications where reliable re-prime is critical." },
  ],
  failureModes: [
    { title: "Cavitation Damage",         desc: "Pitting and erosion on impeller vanes from vapor-bubble collapse. Often the result of insufficient NPSH-available, throttled suction lines, or running far off the BEP." },
    { title: "Bearing Failure",           desc: "Premature bearing replacement is the most common pump repair we see. Causes range from misalignment to contaminated lubricant to running outside the design flow window." },
    { title: "Mechanical Seal Leakage",   desc: "Drips and leaks at the seal face — often a symptom of dry running, abrasive product, or flush plan failure rather than the seal itself being defective." },
    { title: "Impeller Wear & Erosion",   desc: "Abrasive service eats through impeller eyes and vane tips. Hard-facing and tungsten-carbide overlay restore service life." },
    { title: "Shaft Cracks & Breakage",   desc: "Reverse rotation, misalignment, water hammer, and deadhead operation all overload the shaft. We inspect for crack indications during every teardown." },
    { title: "Vibration Problems",        desc: "High vibration is rarely just one thing. We diagnose root cause — unbalance, misalignment, bearing wear, hydraulic instability — and address the actual driver." },
  ],
  process: [
    { step: "01", title: "Complete Teardown",         desc: "Documented as-found dimensions, photos, and condition assessment for every component." },
    { step: "02", title: "Material Verification",     desc: "Material verification on wear components and shaft, with NDT inspection as required." },
    { step: "03", title: "Precision Machining",       desc: "Bore restoration, shaft repair, and wear surface reconditioning — all done in-house." },
    { step: "04", title: "Impeller Balancing",        desc: "Every impeller dynamically balanced to ISO 1940 G2.5 or better. G1.0 available on request." },
    { step: "05", title: "Component Replacement",     desc: "New bearings, seals, gaskets per OEM specification. Hard-facing and wear-ring replacement when required." },
    { step: "06", title: "Final Assembly & Warranty", desc: "Torque verification, clearance documentation, operational test, 24-month written warranty." },
  ],
  brands: [
    "Goulds", "Sulzer", "Flowserve", "ITT", "KSB", "Grundfos", "Gorman-Rupp", "Cornell",
    "Peerless", "Aurora", "Worthington", "Ingersoll Rand", "Allis-Chalmers", "Patterson", "Berkeley", "Floway",
    "Viking", "Tuthill", "Wilden", "Warren Rupp", "Roper", "Blackmer",
  ],
  faqs: [
    { q: "How long does pump repair take?",                                       a: "Standard turnaround is 2-3 weeks from receipt of the unit. Emergency service is available — we can often have a rebuild complete in 5-7 days for true emergencies. Call 346-350-1464." },
    { q: "Do you balance pump impellers?",                                        a: "Yes. Every impeller we rebuild is dynamically balanced to ISO 1940 G2.5 as standard, with G1.0 available on request. We provide as-found and as-left balance reports." },
    { q: "Can you repair pumps from any manufacturer?",                           a: "Yes. We service every major industrial pump brand including Goulds, Sulzer, Flowserve, ITT, KSB, Grundfos, and dozens more. If your pump uses standard ANSI or API construction, we can repair it." },
    { q: "What is your warranty on pump repairs?",                                a: "All pump repairs are backed by our 24-month written warranty — twice the industry standard." },
    { q: "Do you offer hard-facing or tungsten-carbide overlay on impellers?",    a: "Yes. For abrasive service we apply tungsten-carbide hard-facing on impeller eyes, vane tips, and wear surfaces to extend service life dramatically." },
    { q: "How do I get my pump to your shop?",                                    a: "We offer free pickup and delivery throughout the continental U.S. Call 346-350-1464 or fill out the quote form. We handle the logistics." },
    { q: "Do you offer emergency pump repair service?",                           a: "Yes. Our 24/7 emergency line is answered every day. Call 346-350-1464." },
    { q: "Can you diagnose the root cause of pump failures?",                     a: "Yes — every repair includes written failure analysis. Cavitation damage is often a system problem; bearing failures are usually about lubrication or alignment. We address the actual driver." },
  ],
  schema: {
    "@context": "https://schema.org", "@type": "Service",
    "name": "Industrial Pump Repair & Rebuild",
    "serviceType": "Industrial Pump Repair",
    "provider": { "@type": "LocalBusiness", "name": "Kelsey Machine Services", "url": "https://www.kmstx.com", "telephone": "+13463501464", "address": { "@type": "PostalAddress", "addressLocality": "Stafford", "addressRegion": "TX", "postalCode": "77477", "addressCountry": "US" } },
    "areaServed": { "@type": "Country", "name": "United States" },
    "description": "KMS repairs all pump types and brands — centrifugal, vertical turbine, split case, positive displacement. Dynamic balancing, hard-facing, emergency service, nationwide.",
  },
} as const;
